$axure.loadCurrentPage({
  "url":"keywords.html",
  "generationDate":new Date(1424419244001.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ebacd4f92428478cb25ec74b3e1bffa2",
    "type":"Axure:Page",
    "name":"Keywords",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
      "onLoad":{
        "description":"OnLoad",
        "cases":[{
            "description":"Case 1",
            "isNewIfGroup":false,
            "actions":[{
                "action":"fadeWidget",
                "description":"Hide Relevance_tip,<br>edit_task,<br>edit_task,<br>edit_task,<br>edit_task",
                "objectsToFades":[{
                    "objectPath":["f7d82a834b1e41cfb7fffc5e63811ff9"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}},
{
                    "objectPath":["bca6642e8c0e446da82b86c72b39d0c8"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}},
{
                    "objectPath":["d06acf1f0ef548c1b656ac22e1dfa74d"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}},
{
                    "objectPath":["91c70882eecf4e58abc614bca6763587"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}},
{
                    "objectPath":["5d00a908b3f548c88b617d1ab8649c61"],
                    "fadeInfo":{
                      "fadeType":"hide",
                      "options":{
                        "showType":"none"}}}]}]}]}},
    "diagram":{
      "objects":[{
          "id":"c112b74dc4a245c086d8deed34dc9d24",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-10,
              "y":0},
            "size":{
              "width":1347,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"26ab46d2735c4e2aa88758058b9b3476",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-10,
                  "y":0},
                "size":{
                  "width":1347,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_page_1/u2.jpg"}},
{
          "id":"b9d2a79285574bfc9ef1e0a16382e6d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":113},
            "size":{
              "width":153,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe8b979b94d44e058e728cecac41cb57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":113},
                "size":{
                  "width":153,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7112b1a8f2c9461db1a416045dc63cf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":150},
            "size":{
              "width":376,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f439300e671046c6a1e2898043c89c74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":150},
                "size":{
                  "width":376,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/keywords/u4.png"}},
{
          "id":"8191453b80f4440e9888886ee1df2206",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":170},
            "size":{
              "width":518,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"93636c8b80bc4fb3b973a1fbb2e3484d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":170},
                "size":{
                  "width":518,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"facab6cfa7f844e4a604df7c85216f0b",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":93,
              "y":240},
            "size":{
              "width":733,
              "height":144}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4d283f0662147fba8407a636906d3c8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":0},
                "size":{
                  "width":147,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8e5f3f43b27c44b2bf387ecb43109409",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":0},
                    "size":{
                      "width":147,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u9.png"}},
{
              "id":"28f4a6bba1bb43ca82bcc9ddfae99c2e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":30},
                "size":{
                  "width":147,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"97ab0c982af0464abb82e7f22d2f662f",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":30},
                    "size":{
                      "width":147,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u9.png"}},
{
              "id":"e6409189ae4a421c83abf22aa2ad6203",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":147,
                  "y":60},
                "size":{
                  "width":147,
                  "height":84},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"819b9d456ab34f50a0acf33235b1b0ee",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":147,
                      "y":60},
                    "size":{
                      "width":147,
                      "height":84},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u29.png"}},
{
              "id":"5f51d3928f6f49569509319f144202e8",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":0},
                "size":{
                  "width":147,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8aa99ae2790740cbb18ca1ae05307150",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":0},
                    "size":{
                      "width":147,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u9.png"}},
{
              "id":"28acbb2669f848298f2dc91934f4802a",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":30},
                "size":{
                  "width":147,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"de9ee5afcdb64b6482d7daaf9fbc85dc",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":30},
                    "size":{
                      "width":147,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u9.png"}},
{
              "id":"5d27a2bd06a2448cb0318e472a195e91",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":294,
                  "y":60},
                "size":{
                  "width":147,
                  "height":84},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"89238ef100454226bec9421e992223b7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":294,
                      "y":60},
                    "size":{
                      "width":147,
                      "height":84},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u29.png"}},
{
              "id":"724823c2ea75468096c7dc29f1f7c03d",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":441,
                  "y":0},
                "size":{
                  "width":147,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4350cabfe5da4450a5afe02d9fe2edc9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":441,
                      "y":0},
                    "size":{
                      "width":147,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u9.png"}},
{
              "id":"2721c041d95e412598e86f28fda565ff",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":441,
                  "y":30},
                "size":{
                  "width":147,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a0a09b3cc1bc4c9d83956e0dec6317e9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":441,
                      "y":30},
                    "size":{
                      "width":147,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u9.png"}},
{
              "id":"0b2881eeeb8e4d47bf944e0f9fa28bdb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":441,
                  "y":60},
                "size":{
                  "width":147,
                  "height":84},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1ffbee19198048478e5508e891c88f25",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":441,
                      "y":60},
                    "size":{
                      "width":147,
                      "height":84},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u29.png"}},
{
              "id":"48b0e116e7cb4ecc94e9af2d2c5366f7",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":588,
                  "y":0},
                "size":{
                  "width":145,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9a1ec7a560024905bb28613007f54ae4",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":588,
                      "y":0},
                    "size":{
                      "width":145,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u17.png"}},
{
              "id":"1aaaa8099adc4e96bf28c37ae2d47400",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":588,
                  "y":30},
                "size":{
                  "width":145,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ad07f546b8cf436896f50039755da894",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":588,
                      "y":30},
                    "size":{
                      "width":145,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u17.png"}},
{
              "id":"d70c300dea954776b3f5436c67f246cc",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":588,
                  "y":60},
                "size":{
                  "width":145,
                  "height":84},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dfeb2e18fdff49ea9b3b592046e42a43",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":588,
                      "y":60},
                    "size":{
                      "width":145,
                      "height":84},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u37.png"}},
{
              "id":"d56a99e505b249a2b2c83680b953554c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":147,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e877ab1a49e44cbdae1046368a8fab3d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":147,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u9.png"}},
{
              "id":"52ee5fa4ab3b49908e5512d9752d590c",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":147,
                  "height":30},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"75a1c3ada47d411b8d60066080faa583",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":147,
                      "height":30},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u9.png"}},
{
              "id":"4ae43dccd0c149e3aeae7468edf2176b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":147,
                  "height":84},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dc780f19de9b43a999f3efbd2978fff7",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":147,
                      "height":84},
                    "borderFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/keywords/u29.png"}}]},
{
          "id":"00fd7aee704b4242ae8098a42e97fe3b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":215,
              "y":270},
            "size":{
              "width":30,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onMouseHover":{
              "description":"OnMouseHover",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle Relevance_tip",
                      "objectsToFades":[{
                          "objectPath":["f7d82a834b1e41cfb7fffc5e63811ff9"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"f7d82a834b1e41cfb7fffc5e63811ff9",
          "label":"Relevance_tip",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"9px",
            "location":{
              "x":240,
              "y":270},
            "size":{
              "width":71,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"629ce58c016f43a3affa9f17f5bb2a71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"9px",
                "location":{
                  "x":240,
                  "y":270},
                "size":{
                  "width":71,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2fbca66982ce4a089ec3809bd0cde75e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":275},
            "size":{
              "width":20,
              "height":20},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c380298371840c4a4c0f7a1f1b5cb95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":220,
                  "y":275},
                "size":{
                  "width":20,
                  "height":20},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle Relevance_tip",
                      "objectsToFades":[{
                          "objectPath":["f7d82a834b1e41cfb7fffc5e63811ff9"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Hide Relevance_tip",
                      "objectsToFades":[{
                          "objectPath":["f7d82a834b1e41cfb7fffc5e63811ff9"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "images":{
            "normal~":"images/keywords/u42.png"}},
{
          "id":"0339b4628fd344f2ad8e5760185eb00f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":294,
              "y":240},
            "size":{
              "width":40,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle edit_task",
                      "objectsToFades":[{
                          "objectPath":["bca6642e8c0e446da82b86c72b39d0c8"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle edit_task",
                      "objectsToFades":[{
                          "objectPath":["bca6642e8c0e446da82b86c72b39d0c8"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"bca6642e8c0e446da82b86c72b39d0c8",
          "label":"edit_task",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":360,
              "y":245},
            "size":{
              "width":22,
              "height":20},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"217d44d38411483992998a19239b0986",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":360,
                  "y":245},
                "size":{
                  "width":22,
                  "height":20},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/keywords/edit_task_u45.png"}},
{
          "id":"b03c50cab7fe4b0dadea4a8d3bce464c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":440,
              "y":240},
            "size":{
              "width":48,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle edit_task",
                      "objectsToFades":[{
                          "objectPath":["d06acf1f0ef548c1b656ac22e1dfa74d"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle edit_task",
                      "objectsToFades":[{
                          "objectPath":["d06acf1f0ef548c1b656ac22e1dfa74d"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"d06acf1f0ef548c1b656ac22e1dfa74d",
          "label":"edit_task",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":508,
              "y":245},
            "size":{
              "width":22,
              "height":20},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1912a7261d3843bb82745203276e5730",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":508,
                  "y":245},
                "size":{
                  "width":22,
                  "height":20},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/keywords/edit_task_u48.png"}},
{
          "id":"52976251f5044af4b2c080d5a8213b75",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":240},
            "size":{
              "width":108,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle edit_task",
                      "objectsToFades":[{
                          "objectPath":["91c70882eecf4e58abc614bca6763587"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle edit_task",
                      "objectsToFades":[{
                          "objectPath":["91c70882eecf4e58abc614bca6763587"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"91c70882eecf4e58abc614bca6763587",
          "label":"edit_task",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":658,
              "y":245},
            "size":{
              "width":22,
              "height":20},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88d24a66060e4d2c989ed371d0bc56f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":658,
                  "y":245},
                "size":{
                  "width":22,
                  "height":20},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/keywords/edit_task_u48.png"}},
{
          "id":"f1f3ffd01fc246dc8c4d936559039004",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":240},
            "size":{
              "width":108,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onMouseOver":{
              "description":"OnMouseOver",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle edit_task",
                      "objectsToFades":[{
                          "objectPath":["5d00a908b3f548c88b617d1ab8649c61"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]},
            "onMouseOut":{
              "description":"OnMouseOut",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"Toggle edit_task",
                      "objectsToFades":[{
                          "objectPath":["5d00a908b3f548c88b617d1ab8649c61"],
                          "fadeInfo":{
                            "fadeType":"toggle",
                            "options":{
                              "showType":"none"}}}]}]}]}}},
{
          "id":"5d00a908b3f548c88b617d1ab8649c61",
          "label":"edit_task",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFF0000},
            "location":{
              "x":798,
              "y":245},
            "size":{
              "width":22,
              "height":20},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b890aa543f69459387dd8cd58a33ce8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFF0000},
                "location":{
                  "x":798,
                  "y":245},
                "size":{
                  "width":22,
                  "height":20},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/keywords/edit_task_u48.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c112b74dc4a245c086d8deed34dc9d24":{
      "scriptId":"u0"},
    "26ab46d2735c4e2aa88758058b9b3476":{
      "scriptId":"u1"},
    "b9d2a79285574bfc9ef1e0a16382e6d8":{
      "scriptId":"u2"},
    "fe8b979b94d44e058e728cecac41cb57":{
      "scriptId":"u3"},
    "7112b1a8f2c9461db1a416045dc63cf1":{
      "scriptId":"u4"},
    "f439300e671046c6a1e2898043c89c74":{
      "scriptId":"u5"},
    "8191453b80f4440e9888886ee1df2206":{
      "scriptId":"u6"},
    "93636c8b80bc4fb3b973a1fbb2e3484d":{
      "scriptId":"u7"},
    "facab6cfa7f844e4a604df7c85216f0b":{
      "scriptId":"u8"},
    "d56a99e505b249a2b2c83680b953554c":{
      "scriptId":"u9"},
    "e877ab1a49e44cbdae1046368a8fab3d":{
      "scriptId":"u10"},
    "c4d283f0662147fba8407a636906d3c8":{
      "scriptId":"u11"},
    "8e5f3f43b27c44b2bf387ecb43109409":{
      "scriptId":"u12"},
    "5f51d3928f6f49569509319f144202e8":{
      "scriptId":"u13"},
    "8aa99ae2790740cbb18ca1ae05307150":{
      "scriptId":"u14"},
    "724823c2ea75468096c7dc29f1f7c03d":{
      "scriptId":"u15"},
    "4350cabfe5da4450a5afe02d9fe2edc9":{
      "scriptId":"u16"},
    "48b0e116e7cb4ecc94e9af2d2c5366f7":{
      "scriptId":"u17"},
    "9a1ec7a560024905bb28613007f54ae4":{
      "scriptId":"u18"},
    "52ee5fa4ab3b49908e5512d9752d590c":{
      "scriptId":"u19"},
    "75a1c3ada47d411b8d60066080faa583":{
      "scriptId":"u20"},
    "28f4a6bba1bb43ca82bcc9ddfae99c2e":{
      "scriptId":"u21"},
    "97ab0c982af0464abb82e7f22d2f662f":{
      "scriptId":"u22"},
    "28acbb2669f848298f2dc91934f4802a":{
      "scriptId":"u23"},
    "de9ee5afcdb64b6482d7daaf9fbc85dc":{
      "scriptId":"u24"},
    "2721c041d95e412598e86f28fda565ff":{
      "scriptId":"u25"},
    "a0a09b3cc1bc4c9d83956e0dec6317e9":{
      "scriptId":"u26"},
    "1aaaa8099adc4e96bf28c37ae2d47400":{
      "scriptId":"u27"},
    "ad07f546b8cf436896f50039755da894":{
      "scriptId":"u28"},
    "4ae43dccd0c149e3aeae7468edf2176b":{
      "scriptId":"u29"},
    "dc780f19de9b43a999f3efbd2978fff7":{
      "scriptId":"u30"},
    "e6409189ae4a421c83abf22aa2ad6203":{
      "scriptId":"u31"},
    "819b9d456ab34f50a0acf33235b1b0ee":{
      "scriptId":"u32"},
    "5d27a2bd06a2448cb0318e472a195e91":{
      "scriptId":"u33"},
    "89238ef100454226bec9421e992223b7":{
      "scriptId":"u34"},
    "0b2881eeeb8e4d47bf944e0f9fa28bdb":{
      "scriptId":"u35"},
    "1ffbee19198048478e5508e891c88f25":{
      "scriptId":"u36"},
    "d70c300dea954776b3f5436c67f246cc":{
      "scriptId":"u37"},
    "dfeb2e18fdff49ea9b3b592046e42a43":{
      "scriptId":"u38"},
    "00fd7aee704b4242ae8098a42e97fe3b":{
      "scriptId":"u39"},
    "f7d82a834b1e41cfb7fffc5e63811ff9":{
      "scriptId":"u40"},
    "629ce58c016f43a3affa9f17f5bb2a71":{
      "scriptId":"u41"},
    "2fbca66982ce4a089ec3809bd0cde75e":{
      "scriptId":"u42"},
    "4c380298371840c4a4c0f7a1f1b5cb95":{
      "scriptId":"u43"},
    "0339b4628fd344f2ad8e5760185eb00f":{
      "scriptId":"u44"},
    "bca6642e8c0e446da82b86c72b39d0c8":{
      "scriptId":"u45"},
    "217d44d38411483992998a19239b0986":{
      "scriptId":"u46"},
    "b03c50cab7fe4b0dadea4a8d3bce464c":{
      "scriptId":"u47"},
    "d06acf1f0ef548c1b656ac22e1dfa74d":{
      "scriptId":"u48"},
    "1912a7261d3843bb82745203276e5730":{
      "scriptId":"u49"},
    "52976251f5044af4b2c080d5a8213b75":{
      "scriptId":"u50"},
    "91c70882eecf4e58abc614bca6763587":{
      "scriptId":"u51"},
    "88d24a66060e4d2c989ed371d0bc56f7":{
      "scriptId":"u52"},
    "f1f3ffd01fc246dc8c4d936559039004":{
      "scriptId":"u53"},
    "5d00a908b3f548c88b617d1ab8649c61":{
      "scriptId":"u54"},
    "b890aa543f69459387dd8cd58a33ce8d":{
      "scriptId":"u55"}}});