$axure.loadCurrentPage({
  "url":"new_page_1.html",
  "generationDate":new Date(1424419243697.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"67bd4f10259f4610aec39d57dd5fc93a",
    "type":"Axure:Page",
    "name":"New Page 1",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3736fa2182e2497a90117dc24d79b702",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":233},
            "size":{
              "width":577,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e07879f4080b4bc09ade6c161668c7e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":233},
                "size":{
                  "width":577,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f09c3a4f0ba84a1193991e94188685e8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "size":{
              "width":1347,
              "height":75}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23497b650d46476c83bdca7b3d0ed65d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "size":{
                  "width":1347,
                  "height":75}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/new_page_1/u2.jpg"}},
{
          "id":"f8b65ee8cd954c0fbe40efc1bb43b713",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":222},
            "size":{
              "width":304,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3d80032c7a81498ca087015e290b1f15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":222},
                "size":{
                  "width":304,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/new_page_1/u4.jpg"}},
{
          "id":"788f83cdf35f4ee3aaaa0bb116665d2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":780,
              "y":322},
            "size":{
              "width":304,
              "height":76}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f31ee3b10c854d708f1ad340b5447eb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":780,
                  "y":322},
                "size":{
                  "width":304,
                  "height":76}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Home in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"home.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/new_page_1/u6.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "3736fa2182e2497a90117dc24d79b702":{
      "scriptId":"u0"},
    "e07879f4080b4bc09ade6c161668c7e6":{
      "scriptId":"u1"},
    "f09c3a4f0ba84a1193991e94188685e8":{
      "scriptId":"u2"},
    "23497b650d46476c83bdca7b3d0ed65d":{
      "scriptId":"u3"},
    "f8b65ee8cd954c0fbe40efc1bb43b713":{
      "scriptId":"u4"},
    "3d80032c7a81498ca087015e290b1f15":{
      "scriptId":"u5"},
    "788f83cdf35f4ee3aaaa0bb116665d2a":{
      "scriptId":"u6"},
    "f31ee3b10c854d708f1ad340b5447eb1":{
      "scriptId":"u7"}}});